### ISSUE TITLE
Paths are not relative

### ISSUE THREAD

**Issue by conartist6** [therootcompany/walk.js#2]
Docs say that `pathname` is relative, but it seems to actually be absolute. : (

**Comment by coolaj86** [comment]
It's relative to what you pass in, I believe.

If you pass in an absolute path, it won't change it to be relative.

**Comment by conartist6** [comment]
For it not to be a bug, you would have to document that. I'd argue that it's not particularly helpful behavior though, as passing a relative path to your code would mean that it resolves paths relative to `process.cwd()`, something which is liable to create bugs in any tool which searches upwards for a configuration root (or allows one to be specified manually), meaning that `cwd` is not really the thing you want to evaluate your paths relative to.

**Comment by coolaj86** [comment]
So what do you want?

For it to be relative to the first path you pass in?

I wouldn't be against that, except that it would break compatibility and require a major version change.

It would probably require a separate function for the first entry. Actually what would that look like?

If I pass in `./path/to/file.ext` would the path be `./file.ext` or `./`?

And then `./path/to` would be `./` with a name of `to`?

If you come up with an implementation that you like, I will consider the PR and a major version bump...

Should be easy enough to document "migrate to v2.x: we changed what we mean by 'relative' to be relative to the directory to be walked rather than including the path string you gave" or similar.

**Comment by coolaj86** [comment]
> any tool which searches upwards

Hmm... I don't know how _this_ would be useful for that. This only searches down.

I agree a reverse-walk would be useful, but I'm not sure if that belongs here... 

`Walk.reverse(child, walkFn)`... I think I could get behind that.

**Comment by conartist6** [comment]
I just meant upward like npm searches upwards for a `package.json`. Many tools scan files relative to some root directory determined by the presence of a config file. While they may ultimately format their output relative to the user's cwd, the tools themselves need to understand paths relative to their root.

**Comment by conartist6** [comment]
A major version change would seem an appropriate way to handle the change to always calling back with relative paths, even for absolute roots.

**Comment by coolaj86** [comment]
Want to draft something up?

I'm thinking something along these lines: \
(note: top-of-mind, not from existing code)

```js
async function walkFirst(root, walkFn) {
  // get some info about root
  return await walkRecursive(root, '.', details, walkFn);
}

async function walkRecursive(root, rel, details, walkFn) {
  // do stuff
  let nextPath = path.join(rel, details.path)
}

exports.walk = walkFirst;
```

**Comment by conartist6** [comment]
I'll pass. I don't need it right now, and I really do plan to write my own fs walker as part of the iter-tools ecosystem.

**Comment by coolaj86** [comment]
So you just came here to complain about something you don't need for fun?

That's okay. I do that sometimes too.

**Comment by conartist6** [comment]
To be fair at the time I was planning to use it in pnpm, and now it looks like I may still need to.

**Comment by conartist6** [comment]
Sorry, I have been rude. I didn't set out to be. I did not understand that your focus was on minimalism. I am looking for a workhorse of a package that I will want to use and evolve for many years.
