### ISSUE TITLE
Question about  @root/walk vs @nodelib/fs.walk

### ISSUE THREAD

**Issue by ivanjeremic** [therootcompany/walk.js#4]
I really love `@root/walk` and it works very well for me but I found `@nodelib/fs.walk` on npm and was confused about the 20+ million downloads, is this some low level lib and because of it the many downloads? Also interesting to know would be, is it using maybe more modern and faster techniques than `@root/walk`?

The only reason I ask is maybe something can be improved in `@root/walk` I honestly find the API friendlier here.

**Comment by coolaj86** [comment]
Thanks for the kind words.

Originally I wrote `walk` and that was quite popular for many years, though I think other libraries have since become more popular.

I wrote `@root/walk` over a year ago because I wanted the simplicity of Go's `filepath.Walk` and I was curious to see if a very simple implementation like that could be significantly smaller, and easier to understand.

I haven't posted this on Reddit or done anything to make it popular, other than putting a notice in the README of the original `walk`.

I believe that this makes use of the absolute latest features (particularly the newer directory entries object) that make this much more efficient than prior implementations for a broad range of uses - but I don't have benchmarks and I haven't done any performance "hacks" - no micro-optimizations or anything that would harm code readability.

If you'd like to see it become more popular and you use the sorts of social media that people are using these days for node modules, please share and and let's see what happens.

That all said, it's fine if this doesn't become wildly popular. Node is (mostly) past the days where a new implementation of some functionality will compete to be the new standard everyone uses.

I'm happy that this is working well for me, for my clients, and for people like you, and that's enough for me. 🙂
